In [2]:
import torch
import torch.nn as nn

In [4]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "mps")

In [79]:
# prepare the tensor
# tensor of 64 x 344 as input

n_classes = 4
batch_size = 4

embeddings = torch.arange(batch_size*344).reshape(batch_size, 344)
n_layers = torch.ceil(torch.log2(torch.tensor(n_classes))).int().item()
choices = torch.zeros(n_layers * batch_size, dtype=torch.bool, device=device).reshape(batch_size, n_layers)

modifier_bias = nn.Parameter(torch.randn(344, )).to(device)        



NameError: name 'self' is not defined

In [71]:
def classifier(_):
    return torch.rand(batch_size * 2).reshape(batch_size, 2)

def get_int_parameters(i, softmax_index):
    print(softmax_index)
    return (2 * i) + softmax_index

def DiffSoftmax(logits, tau=1.0, hard=False, dim=-1):
    y_soft = (logits / tau).softmax(dim)
    if hard:
        # Straight through.
        index = y_soft.max(dim, keepdim=True)[1]
        y_hard = torch.zeros_like(logits, memory_format=torch.legacy_contiguous_format).scatter_(dim, index, 1.0)
        ret = y_hard - y_soft.detach() + y_soft
    else:
        # Reparametrization trick.
        ret = y_soft
    return ret

In [75]:
# prepare the tensor
# tensor of 64 x 344 as input

n_classes = 4
batch_size = 4

embeddings = torch.arange(batch_size*344).reshape(batch_size, 344)
n_layers = torch.ceil(torch.log2(torch.tensor(n_classes))).int().item()
choices = torch.zeros(n_layers * batch_size, dtype=torch.bool, device=device).reshape(batch_size, n_layers)

print(choices)

i = 0

tensor([[False, False],
        [False, False],
        [False, False],
        [False, False]], device='mps:0')


In [77]:
x = classifier(embeddings)
print(x)
softmax = DiffSoftmax(x, tau=1.0, hard=True, dim=-1)
choices[:, i:i+1] = softmax[:, i:i+1]
print(choices)
shift_index = get_int_parameters(i, softmax[:, i:i+1])
print(shift_index)
#x = x + self.modifier_bias[shift_index]

i +=1 

tensor([[0.3169, 0.2540],
        [0.9820, 0.0544],
        [0.2194, 0.3662],
        [0.5643, 0.0096]])
tensor([[False, False],
        [ True, False],
        [False,  True],
        [ True, False]], device='mps:0')
tensor([[0.],
        [0.],
        [1.],
        [0.]])
tensor([[2.],
        [2.],
        [3.],
        [2.]])


In [46]:
# recurrent classifier that we need to learn
# first step is to learn the first part of the classifier
# what if instead that is also a learnable parameters over the different runs of the classifier

n_layers = torch.ceil(torch.log2(torch.tensor(self.input))).int().item() -1
# emtpty tensor of size n_layers, batch_size of datatype torch.bool

for i in range(n_layers):
    x = self.modules["classifier"](x)
    softmax = self.DiffSoftmax(x, tau=1.0, hard=False, dim=-1)
    choices[i][:] = torch.bernoulli(softmax[:,1])
    shift_index = self.get_int_parameters(i, softmax)
    x = x + self.modifier_bias[shift_index]
    
return x

NameError: name 'self' is not defined

In [3]:
t = torch.tensor([[1, 2], [3.0, 4]])

In [5]:
torch.gather(t, 1, torch.tensor([[0, 0], [1.0, 0]]))

RuntimeError: gather(): Expected dtype int64 for index

In [20]:

a = [0,0,0,0,0]

b = [0,0,0,1,0]

start = 0
mid = 2
end = 4

max = 10

res = torch.stack([torch.cat([torch.zeros(2*x), torch.tensor(b), torch.zeros(2*(max-x-1))], dim=0) for x in range(4)], dim=0)
print(res)

tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.]])


In [58]:
device = 'mps'

indexes_int = torch.tensor([0,1])

start = indexes_int * 10
end = (indexes_int + 1) * 10

output_tensor = torch.zeros(2, 100, device=device)

# # Use 'torch.arange' and 'torch.stack' for creating the sequence tensors
to_add = torch.stack([torch.arange(start[i], end[i], device=device) for i in range(len(indexes_int))])     


In [59]:
print(output_tensor)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.]], device='mps:0')


In [65]:
print(to_add)
print(to_add.dtype)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]], device='mps:0')
torch.int64


In [62]:
i = torch.tensor([0,1,2,3,4,5,6,7,8,9]).float().to(device)

In [63]:
output_tensor.dtype

torch.float32

In [66]:
output_tensor.scatter_(1, to_add, i)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)