In [1]:
import json
f = open('parent_to_child_class_from_0_to_5.json')
parent_to_child_class_from_0_to_5 = json.load(f)
print(parent_to_child_class_from_0_to_5)

{'11': {'15': 0, '19': 1, '21': 2, '31': 3, '38': 4}, '15': {'27': 0, '29': 1, '44': 2, '78': 3, '93': 4}, '4': {'0': 0, '51': 1, '53': 2, '57': 3, '83': 4}, '14': {'2': 0, '11': 1, '35': 2, '46': 3, '98': 4}, '1': {'1': 0, '32': 1, '67': 2, '73': 3, '91': 4}, '5': {'22': 0, '39': 1, '40': 2, '86': 3, '87': 4}, '18': {'8': 0, '13': 1, '48': 2, '58': 3, '90': 4}, '3': {'9': 0, '10': 1, '16': 2, '28': 3, '61': 4}, '10': {'23': 0, '33': 1, '49': 2, '60': 3, '71': 4}, '17': {'47': 0, '52': 1, '56': 2, '59': 3, '96': 4}, '2': {'54': 0, '62': 1, '70': 2, '82': 3, '92': 4}, '9': {'12': 0, '17': 1, '37': 2, '68': 3, '76': 4}, '8': {'3': 0, '42': 1, '43': 2, '88': 3, '97': 4}, '16': {'36': 0, '50': 1, '65': 2, '74': 3, '80': 4}, '6': {'5': 0, '20': 1, '25': 2, '84': 3, '94': 4}, '12': {'34': 0, '63': 1, '64': 2, '66': 3, '75': 4}, '19': {'41': 0, '69': 1, '81': 2, '85': 3, '89': 4}, '7': {'6': 0, '7': 1, '14': 2, '18': 3, '24': 4}, '13': {'26': 0, '45': 1, '77': 2, '79': 3, '99': 4}, '0': {'4':

In [2]:
from __future__ import print_function
from PIL import Image
import os
import os.path
import errno
import numpy as np
import sys
import torch
if sys.version_info[0] == 2:
    import cPickle as pickle
else:
    import pickle

import torch.utils.data as data
from torchvision.datasets.utils import download_url, check_integrity
import torchvision.transforms as tt
from torchvision import datasets, transforms
import torchvision

class CIFAR10(data.Dataset):
    """`CIFAR10 <https://www.cs.toronto.edu/~kriz/cifar.html>`_ Dataset.
    Args:
        root (string): Root directory of dataset where directory
            ``cifar-10-batches-py`` exists.
        train (bool, optional): If True, creates dataset from training set, otherwise
            creates from test set.
        transform (callable, optional): A function/transform that  takes in an PIL image
            and returns a transformed version. E.g, ``transforms.RandomCrop``
        target_transform (callable, optional): A function/transform that takes in the
            target and transforms it.
        download (bool, optional): If true, downloads the dataset from the internet and
            puts it in root directory. If dataset is already downloaded, it is not
            downloaded again.
    """
    base_folder = 'cifar-10-batches-py'
    url = "https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz"
    filename = "cifar-10-python.tar.gz"
    tgz_md5 = 'c58f30108f718f92721af3b95e74349a'
    train_list = [
        ['data_batch_1', 'c99cafc152244af753f735de768cd75f'],
        ['data_batch_2', 'd4bba439e000b95fd0a9bffe97cbabec'],
        ['data_batch_3', '54ebc095f3ab1f0389bbae665268c751'],
        ['data_batch_4', '634d18415352ddfa80567beed471001a'],
        ['data_batch_5', '482c414d41f54cd18b22e5b47cb7c3cb'],
    ]

    test_list = [
        ['test_batch', '40351d587109b95175f43aff81a1287e'],
    ]

    meta = {
        "filename": "batches.meta",
        "key": "label_names",
        "md5": "5ff9c542aee3614f3951f8cda6e48888",
    }


    def __init__(self, root, train=True,
                 transform=None, target_transform=None,
                 download=False, coarse=False, coarseNumber=None):
        self.root = os.path.expanduser(root)
        self.transform = transform
        self.target_transform = target_transform
        self.train = train  # training set or test set
        self.coarse = coarse

        if download:
            self.download()

        if not self._check_integrity():
            raise RuntimeError('Dataset not found or corrupted.' +
                               ' You can use download=True to download it')

        # now load the picked numpy arrays
        if self.train:
            self.train_data = []
            self.train_labels = []
            self.train_coarse_labels = []
            for fentry in self.train_list:
                f = fentry[0]
                file = os.path.join(self.root, self.base_folder, f)
                fo = open(file, 'rb')
                if sys.version_info[0] == 2:
                    entry = pickle.load(fo)
                else:
                    entry = pickle.load(fo, encoding='latin1')
                self.train_data.append(entry['data'])
                if 'labels' in entry:
                    self.train_labels += entry['labels']
                else:
                    self.train_labels += entry['fine_labels']
                    if self.coarse:
                        self.train_coarse_labels += entry['coarse_labels']
                fo.close()
            ###
            new_train_coarse_labels=[]
            new_train_fine_labels=[]
            new_train_data=[]
            #print("before data Train",np.concatenate(self.train_data))
            #print(len(self.train_data))
            #print("before fine Train",self.train_labels)
            #print(len(self.train_labels))
            #print("before coarse Train",self.train_coarse_labels)
            #print(len(self.train_coarse_labels))
            for data, fine,coarse in zip(self.train_data[0],self.train_labels, self.train_coarse_labels):
                if coarse==coarseNumber:
                    new_train_data.append(data)
                    new_train_fine_labels.append(parent_to_child_class_from_0_to_5[str(coarseNumber)][str(fine)])
                    new_train_coarse_labels.append(coarseNumber)
            # print("now coarse ",new_train_coarse_labels)
            # print("now fine ",new_train_fine_labels)
            # print(len(new_train_coarse_labels))
            # print(len(new_train_fine_labels))
            # print("============")
            # self.train_data=new_train_data
            print(parent_to_child_class_from_0_to_5[str(coarseNumber)])
            self.train_data=np.array([np.array(xi) for xi in new_train_data])
            self.train_labels=new_train_fine_labels
            self.train_coarse_labels=new_train_coarse_labels
            print(self.train_labels)
            # print(" ",self.train_data)
            # print(" ",self.train_labels)
            # print(" ",self.train_coarse_labels)
            ###
            # print("after data Train",self.train_data)
            # print(len(self.train_data))
            #print("after fine Train",self.train_labels)
            #print(len(self.train_labels))
            #print("after coarse Train",self.train_coarse_labels)
            #self.train_data = np.concatenate(self.train_data)
            self.train_data = self.train_data.reshape((len(new_train_data), 3, 32, 32))
            self.train_data = self.train_data.transpose((0, 2, 3, 1))  # convert to HWC
        else:
            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
            f = self.test_list[0][0]
            file = os.path.join(self.root, self.base_folder, f)
            fo = open(file, 'rb')
            if sys.version_info[0] == 2:
                entry = pickle.load(fo)
            else:
                entry = pickle.load(fo, encoding='latin1')
            self.test_data = entry['data']

            if 'labels' in entry:
                self.test_labels = entry['labels']
            else:
                self.test_labels = entry['fine_labels']
                if self.coarse:
                    self.test_coarse_labels = entry['coarse_labels']
                new_test_coarse_labels=[]
                new_test_fine_labels=[]
                new_test_data=[]
                # print("before fine ",entry['fine_labels'])
                # print(len(entry['fine_labels']))
                # print("before coarse ",entry['coarse_labels'])
                # print(len(entry['coarse_labels']))
                for data, fine,coarse in zip(self.test_data,self.test_labels, self.test_coarse_labels):
                    if coarse==coarseNumber:
                        new_test_data.append(data)
                        new_test_fine_labels.append(parent_to_child_class_from_0_to_5[str(coarseNumber)][str(fine)])
                        new_test_coarse_labels.append(coarseNumber)
                # print("now coarse ",new_test_coarse_labels)
                # print("now fine ",new_test_fine_labels)
                # print(len(new_test_coarse_labels))
                # print(len(new_test_fine_labels))
                # print("============")
                # print("now data ",new_test_data)
                # print(len(new_test_data))
                # print("self test data before",self.test_data)
                # print("test data type before", type(self.test_data))
                # print("shape of test data before ", self.test_data.shape)
                self.test_data=np.array([np.array(xi) for xi in new_test_data])
                # print("test data type after", type(self.test_data))
                # print("shape of test data after ", self.test_data.shape)
                self.test_labels=new_test_fine_labels
                self.test_coarse_labels=new_test_coarse_labels
            fo.close()
            self.test_data = self.test_data.reshape((len(new_test_data), 3, 32, 32))
            self.test_data = self.test_data.transpose((0, 2, 3, 1))  # convert to HWC

    def __getitem__(self, index):
        """
        Args:
            index (int): Index
        Returns:
            tuple: (image, target) where target is index of the target class.
        """
        if self.train:
            img, target = self.train_data[index], self.train_labels[index]
            if self.coarse:
                coarse_target = self.train_coarse_labels[index]
        else:
            img, target = self.test_data[index], self.test_labels[index]
            if self.coarse:
                coarse_target = self.test_coarse_labels[index]

        # doing this so that it is consistent with all other datasets
        # to return a PIL Image
        img = Image.fromarray(img)

        if self.transform is not None:
            img = self.transform(img)

        if self.target_transform is not None:
            target = self.target_transform(target)
        if not self.coarse:
            return img, target
        else:
            return img, target, coarse_target

    def __len__(self):
        if self.train:
            return len(self.train_data)
        else:
            return len(self.test_data)

    def _check_integrity(self):
        root = self.root
        for fentry in (self.train_list + self.test_list):
            filename, md5 = fentry[0], fentry[1]
            fpath = os.path.join(root, self.base_folder, filename)
            if not check_integrity(fpath, md5):
                return False
        return True

    def download(self):
        import tarfile

        if self._check_integrity():
            print('Files already downloaded and verified')
            return

        root = self.root
        download_url(self.url, root, self.filename, self.tgz_md5)

        # extract file
        cwd = os.getcwd()
        tar = tarfile.open(os.path.join(root, self.filename), "r:gz")
        os.chdir(root)
        tar.extractall()
        tar.close()
        os.chdir(cwd)


class CIFAR100(CIFAR10):
    """`CIFAR100 <https://www.cs.toronto.edu/~kriz/cifar.html>`_ Dataset.
    This is a subclass of the `CIFAR10` Dataset.
    """
    base_folder = 'cifar-100-python'
    url = "https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz"
    filename = "cifar-100-python.tar.gz"
    tgz_md5 = 'eb9058c3a382ffc7106e4002c42a8d85'
    train_list = [
        ['train', '16019d7e3df5f24257cddd939b257f8d'],
    ]

    test_list = [
        ['test', 'f0ef6b0ae62326f3e7ffdfab6717acfc'],
    ]


In [3]:
transform_train = tt.Compose([tt.RandomCrop(32, padding=4,padding_mode='reflect'), 
                         tt.RandomHorizontalFlip(), 
                         tt.ToTensor(), 
                         #tt.Normalize(mean,std,inplace=True) 
                         ]
                         )
transform_test = tt.Compose([tt.ToTensor(), 
                             #tt.Normalize(mean,std)
                             ])

In [4]:
batch_size = 400
epochs = 120
max_lr = 0.001
grad_clip = 0.01
weight_decay =0.001
opt_func = torch.optim.Adam

In [5]:
train_data = CIFAR100('./data', train=True,
                 transform=transform_train,
                 download=True, coarse=True, coarseNumber=2)
test_data = CIFAR100('./data', train=False,
                 transform=transform_test,
                 download=True, coarse=True, coarseNumber=2)

train_length = train_data.__len__() # Length training dataset
train_indices = np.arange(train_length)
    
train_loader = torch.utils.data.DataLoader(
                        train_data, 
                        batch_size=batch_size, 
                        num_workers=2,
                        pin_memory=True,
                    )

test_loader = torch.utils.data.DataLoader(
                        test_data, 
                        batch_size=batch_size*2,
                        num_workers=2,
                        pin_memory=True
                    )

Files already downloaded and verified
{'54': 0, '62': 1, '70': 2, '82': 3, '92': 4}
[3, 2, 4, 2, 1, 3, 0, 1, 1, 0, 0, 3, 3, 3, 3, 0, 0, 1, 3, 4, 2, 0, 2, 3, 3, 0, 0, 4, 1, 2, 1, 1, 0, 3, 0, 4, 2, 1, 1, 1, 2, 2, 4, 4, 2, 1, 0, 3, 1, 1, 0, 1, 2, 0, 0, 3, 4, 0, 0, 0, 4, 3, 3, 0, 0, 0, 0, 2, 1, 0, 3, 2, 4, 4, 1, 3, 0, 2, 4, 4, 0, 2, 2, 1, 1, 3, 1, 2, 1, 4, 4, 4, 3, 0, 4, 1, 2, 3, 3, 1, 4, 2, 2, 4, 1, 4, 3, 2, 1, 0, 4, 4, 1, 1, 2, 1, 0, 0, 2, 2, 4, 2, 2, 3, 3, 2, 1, 0, 0, 1, 2, 4, 0, 1, 2, 3, 0, 4, 4, 1, 0, 4, 1, 2, 2, 1, 2, 3, 2, 2, 0, 1, 2, 3, 1, 4, 0, 3, 3, 0, 4, 4, 3, 1, 2, 3, 3, 0, 3, 4, 1, 4, 3, 3, 1, 4, 4, 1, 3, 2, 1, 1, 3, 3, 1, 1, 1, 3, 2, 0, 2, 0, 0, 0, 3, 4, 3, 2, 2, 1, 4, 3, 1, 2, 0, 4, 1, 3, 2, 4, 1, 4, 1, 0, 3, 0, 4, 3, 4, 0, 0, 4, 2, 1, 0, 1, 1, 1, 2, 0, 4, 2, 0, 2, 4, 2, 1, 1, 2, 4, 3, 1, 2, 2, 2, 4, 2, 0, 4, 3, 1, 0, 0, 4, 2, 4, 3, 3, 2, 1, 3, 0, 4, 0, 1, 3, 4, 0, 4, 3, 3, 1, 3, 3, 2, 1, 4, 0, 2, 3, 3, 2, 2, 0, 4, 1, 1, 2, 3, 4, 4, 0, 3, 2, 2, 1, 2, 3, 2, 3, 1, 3, 1, 3, 2, 

In [6]:
def get_default_device():
    """Pick GPU if available, else CPU"""
    if torch.cuda.is_available():
        return torch.device('cuda')
    else:
        return torch.device('cpu')
    
def to_device(data, device):
    """Move tensor(s) to chosen device"""
    if isinstance(data, (list,tuple)):
        return [to_device(x, device) for x in data]
    return data.to(device, non_blocking=True)

class DeviceDataLoader():
    """Wrap a dataloader to move data to a device"""
    def __init__(self, dl, device):
        self.dl = dl
        self.device = device
        
    def __iter__(self):
        """Yield a batch of data after moving it to device"""
        for b in self.dl: 
            yield to_device(b, self.device)

    def __len__(self):
        """Number of batches"""
        return len(self.dl)

In [7]:
device = get_default_device()
device

device(type='cuda')

In [8]:
trainloader = DeviceDataLoader(train_loader, device)
testloader = DeviceDataLoader(test_loader, device)

In [9]:
import torch.nn as nn
import torch.nn.functional as F

In [10]:
def accuracy(outputs, labels):
    _, preds = torch.max(outputs, dim=1)
    return torch.tensor(torch.sum(preds == labels).item() / len(preds))

class ImageClassificationBase(nn.Module):
    def __init__(self, fine):
        super(ImageClassificationBase, self).__init__()
        self.fine = fine
        #self.parent_to_child_class={}
        self.unique_outs=[]
    
    def training_step(self, batch):
        images, fine, coarse = batch
        if self.fine:
            labels=fine
        else:
            labels=coarse
        out = self(images)                  # Generate predictions
        loss = F.cross_entropy(out, labels) # Calculate loss
        return loss
    
    def validation_step(self, batch):
        images, fine, coarse = batch 

        #print("coarse ", coarse)
        #print("fine ", fine)    
        if self.fine:
            labels=fine
        else:
            labels=coarse
        out = self(images)
        #print("out shape ",out.shape)
        #print("out first three", out[:3,:])  
        #print("labels shape ",labels.shape)
        #print("labels first three", labels[:3])
        #labels=labels.cpu().apply_(lambda val: dict.get(val)).to(labels.device)
        loss = F.cross_entropy(out, labels)   # Calculate loss
        acc = accuracy(out, labels)           # Calculate accuracy
        return {'val_loss': loss.detach(), 'val_acc': acc}
        
    def validation_epoch_end(self, outputs):
        batch_losses = [x['val_loss'] for x in outputs]
        epoch_loss = torch.stack(batch_losses).mean()   # Combine losses
        batch_accs = [x['val_acc'] for x in outputs]
        epoch_acc = torch.stack(batch_accs).mean()      # Combine accuracies
        return {'val_loss': epoch_loss.item(), 'val_acc': epoch_acc.item()}
    
    def epoch_end(self, epoch, result):
        print("Epoch [{}], last_lr: {:.5f}, train_loss: {:.4f}, val_loss: {:.4f}, val_acc: {:.4f}".format(
            epoch, result['lrs'][-1], result['train_loss'], result['val_loss'], result['val_acc']))
        
def conv_block(in_channels, out_channels, pool=False):
    layers = [nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1), 
              nn.BatchNorm2d(out_channels), 
              nn.ReLU(inplace=True)]
    if pool: layers.append(nn.MaxPool2d(2))
    return nn.Sequential(*layers)

class ResNet9(ImageClassificationBase):
    def __init__(self, in_channels, num_classes, fine):
        super().__init__(fine)
        
        self.conv1 = conv_block(in_channels, 64)
        self.conv2 = conv_block(64, 128, pool=True) 
        self.res1 = nn.Sequential(conv_block(128, 128), conv_block(128, 128)) 
        
        self.conv3 = conv_block(128, 256, pool=True)
        self.conv4 = conv_block(256, 512, pool=True) 
        self.res2 = nn.Sequential(conv_block(512, 512), conv_block(512, 512)) 
        self.conv5 = conv_block(512, 1028, pool=True) 
        self.res3 = nn.Sequential(conv_block(1028, 1028), conv_block(1028, 1028))  
        
        self.classifier_parent = nn.Sequential(nn.MaxPool2d(2), # 1028 x 1 x 1
                                        nn.Flatten(), # 1028 
                                        nn.Linear(1028, 20))
        
        self.classifier_child = nn.Sequential(self.classifier_parent,
                                nn.ReLU(),
                                nn.Linear(20, num_classes)) # 1028 -> 100
        
        # -------------------

        # self.thousand_tofifty=nn.Sequential(nn.MaxPool2d(2), # 1028 x 1 x 1
        #                                 nn.Flatten(), # 1028 
        #                                 nn.Linear(1028, 50))  
        
        # self.classifier = nn.Sequential(self.thousand_tofifty,
        #                                 nn.ReLU(),
        #                                 nn.Linear(50, num_classes)
        #                                 ) # 1028 -> 100
        
    def forward(self, xb):
        out = self.conv1(xb)
        out = self.conv2(out)
        out = self.res1(out) + out
        out = self.conv3(out)
        out = self.conv4(out)
        out = self.res2(out) + out
        out = self.conv5(out)
        out = self.res3(out) + out
        out = self.classifier_child(out)
        #parent=out.argmax(dim=1, keepdim=True)
        #print("parent shape ", parent.shape)
        #delete=delete.cpu().numpy().argmax()
        #if delete not in self.unique_outs:
        #    self.unique_outs.append(delete)
        #print(self.unique_outs)
        return out

#model100 = to_device(ResNet9(3, 100, True), device)
#model100


In [11]:
@torch.no_grad()
def evaluate(model, test_loader):
    model.eval()
    outputs = [model.validation_step(batch) for batch in test_loader]
    return model.validation_epoch_end(outputs)

def get_lr(optimizer):
    for param_group in optimizer.param_groups:
        return param_group['lr']

def fit_one_cycle(epochs, max_lr, model, train_loader, test_loader, 
                  weight_decay=0, grad_clip=None, opt_func=torch.optim.SGD):
    torch.cuda.empty_cache()
    history = []
    
    # Set up cutom optimizer with weight decay
    optimizer = opt_func(model.parameters(), max_lr, weight_decay=weight_decay)
    # Set up one-cycle learning rate scheduler
    sched = torch.optim.lr_scheduler.OneCycleLR(optimizer, max_lr, epochs=epochs, 
                                                steps_per_epoch=len(train_loader))
    
    for epoch in range(epochs):
        # Training Phase 
        model.train()
        train_losses = []
        lrs = []
        for batch in train_loader:
            loss = model.training_step(batch)
            train_losses.append(loss)
            loss.backward()
            
            # Gradient clipping
            if grad_clip: 
                nn.utils.clip_grad_value_(model.parameters(), grad_clip)
            
            optimizer.step()
            optimizer.zero_grad()
            
            # Record & update learning rate
            lrs.append(get_lr(optimizer))
            sched.step()
        
        # Validation phase
        result = evaluate(model, test_loader)
        result['train_loss'] = torch.stack(train_losses).mean().item()
        result['lrs'] = lrs
        model.epoch_end(epoch, result)
        history.append(result)
    return history

In [12]:
import time
from sklearn.metrics import *

In [13]:
# Generate testing accuracy, predicted label, confusion matrix, and table for classification report
def test_label_predictions(model, device, test_loader, fine):
    model.eval()
    actuals = []
    predictions = []
    with torch.no_grad():
        if fine:
            for data, target, _ in test_loader:
                data, target = data.to(device), target.to(device)
                output = model(data)
                prediction = output.argmax(dim=1, keepdim=True)
                print("predicted ", prediction, " actual: ", target)
                actuals.extend(target.view_as(prediction))
                predictions.extend(prediction)
        else:
            for data, _, target in test_loader:
                data, target = data.to(device), target.to(device)
                output = model(data)
                prediction = output.argmax(dim=1, keepdim=True)
                print("predicted ", prediction, " actual: ", target)
                actuals.extend(target.view_as(prediction))
                predictions.extend(prediction)

    return [i.item() for i in actuals], [i.item() for i in predictions]

In [14]:
from torchsummary import summary

#print(summary(model100,(3, 32, 32)))

-----------------------------------------------------------------------------------

In [24]:
model20To100 = ResNet9(3, 100, True)
model20To100.load_state_dict(torch.load('group20To100_parent_and_child_pretrained_model.h5'))
for param in model20To100.parameters():
    param.requires_grad=False

model20To100.classifier_child = nn.Sequential(model20To100.classifier_parent,
                                        nn.ReLU(),
                                        nn.Linear(20, 10),
                                        nn.ReLU(),
                                        nn.Linear(10, 5)
                                        )
                                        
model20To100=to_device(model20To100, device)
model20To100

ResNet9(
  (conv1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
  )
  (conv2): Sequential(
    (0): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (res1): Sequential(
    (0): Sequential(
      (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU(inplace=True)
    )
    (1): Sequential(
      (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU(inplace=Tr

In [25]:
print(summary(model20To100,(3, 32, 32)))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1           [-1, 64, 32, 32]           1,792
       BatchNorm2d-2           [-1, 64, 32, 32]             128
              ReLU-3           [-1, 64, 32, 32]               0
            Conv2d-4          [-1, 128, 32, 32]          73,856
       BatchNorm2d-5          [-1, 128, 32, 32]             256
              ReLU-6          [-1, 128, 32, 32]               0
         MaxPool2d-7          [-1, 128, 16, 16]               0
            Conv2d-8          [-1, 128, 16, 16]         147,584
       BatchNorm2d-9          [-1, 128, 16, 16]             256
             ReLU-10          [-1, 128, 16, 16]               0
           Conv2d-11          [-1, 128, 16, 16]         147,584
      BatchNorm2d-12          [-1, 128, 16, 16]             256
             ReLU-13          [-1, 128, 16, 16]               0
           Conv2d-14          [-1, 256,

In [26]:
# Initial evaluation
history = evaluate(model20To100, testloader)


In [27]:
history

{'val_loss': 4.530359268188477, 'val_acc': 0.20800000429153442}

In [29]:
# Fitting the first 1/4 epochs
current_time=time.time()
history += fit_one_cycle(int(epochs), max_lr, model20To100, trainloader, testloader, 
                             grad_clip=grad_clip, 
                             weight_decay=weight_decay, 
                             opt_func=opt_func)

Epoch [0], last_lr: 0.00004, train_loss: 0.7109, val_loss: 1.1067, val_acc: 0.5900
Epoch [1], last_lr: 0.00005, train_loss: 0.7085, val_loss: 1.1086, val_acc: 0.5860
Epoch [2], last_lr: 0.00005, train_loss: 0.7046, val_loss: 1.1070, val_acc: 0.5840
Epoch [3], last_lr: 0.00007, train_loss: 0.7130, val_loss: 1.1061, val_acc: 0.5880
Epoch [4], last_lr: 0.00008, train_loss: 0.7148, val_loss: 1.1087, val_acc: 0.5860
Epoch [5], last_lr: 0.00010, train_loss: 0.7291, val_loss: 1.1092, val_acc: 0.5880
Epoch [6], last_lr: 0.00012, train_loss: 0.7152, val_loss: 1.1079, val_acc: 0.5880
Epoch [7], last_lr: 0.00015, train_loss: 0.7434, val_loss: 1.1109, val_acc: 0.5880
Epoch [8], last_lr: 0.00018, train_loss: 0.7225, val_loss: 1.1074, val_acc: 0.5880
Epoch [9], last_lr: 0.00021, train_loss: 0.7164, val_loss: 1.1066, val_acc: 0.5900
Epoch [10], last_lr: 0.00024, train_loss: 0.7186, val_loss: 1.1062, val_acc: 0.5900
Epoch [11], last_lr: 0.00028, train_loss: 0.7004, val_loss: 1.1077, val_acc: 0.5880
Ep

KeyboardInterrupt: 

In [120]:
# Fitting the second 1/4 epochs
history += fit_one_cycle(int(epochs/4), max_lr/10, model20To100, trainloader, testloader, 
                             grad_clip=grad_clip, 
                             weight_decay=weight_decay, 
                             opt_func=opt_func)

Epoch [0], last_lr: 0.00001, train_loss: 0.6713, val_loss: 0.8973, val_acc: 0.6300
Epoch [1], last_lr: 0.00001, train_loss: 0.6675, val_loss: 0.8991, val_acc: 0.6220
Epoch [2], last_lr: 0.00003, train_loss: 0.6638, val_loss: 0.8992, val_acc: 0.6280
Epoch [3], last_lr: 0.00004, train_loss: 0.6733, val_loss: 0.8980, val_acc: 0.6260
Epoch [4], last_lr: 0.00006, train_loss: 0.6794, val_loss: 0.8981, val_acc: 0.6280
Epoch [5], last_lr: 0.00008, train_loss: 0.6701, val_loss: 0.8978, val_acc: 0.6300
Epoch [6], last_lr: 0.00009, train_loss: 0.6753, val_loss: 0.9002, val_acc: 0.6280
Epoch [7], last_lr: 0.00010, train_loss: 0.6699, val_loss: 0.8992, val_acc: 0.6300
Epoch [8], last_lr: 0.00010, train_loss: 0.6746, val_loss: 0.8988, val_acc: 0.6260
Epoch [9], last_lr: 0.00010, train_loss: 0.6802, val_loss: 0.9032, val_acc: 0.6300
Epoch [10], last_lr: 0.00010, train_loss: 0.6707, val_loss: 0.8991, val_acc: 0.6300
Epoch [11], last_lr: 0.00010, train_loss: 0.6721, val_loss: 0.9000, val_acc: 0.6280
Ep

TypeError: unsupported operand type(s) for +=: 'dict' and 'list'

In [30]:
# Saving the model to h5 file
torch.save(model20To100.state_dict(), 'group20To100_parent_child_60percent_acc_pretrained_model.h5')

In [31]:
class BiasLayer(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
        bias_value = torch.randn((1))
        self.bias_layer = torch.nn.Parameter(bias_value)
    
    def forward(self, x):
        return x + self.bias_layer

In [35]:
model20To100_bias_learn_only = ResNet9(3, 100, True)
model20To100_bias_learn_only.classifier_child = nn.Sequential(model20To100_bias_learn_only.classifier_parent,
                                        nn.ReLU(),
                                        nn.Linear(20, 10),
                                        nn.ReLU(),
                                        nn.Linear(10, 5)
                                        )
model20To100_bias_learn_only.load_state_dict(torch.load('group20To100_parent_child_60percent_acc_pretrained_model.h5'))
for param in model20To100_bias_learn_only.parameters():
    param.requires_grad=False



In [58]:
class Morning_english_greetings(ResNet9):

    def __init__(self, resnet9):
        super(ResNet9, self).__init__(resnet9.fine)
        self.resnet9=resnet9
        self.fine=resnet9.fine
        for param in self.resnet9.parameters():
            param.requires_grad=False
        self.bias = nn.Parameter(torch.ones(1))

    def forward(self):
        return self.resnet9.forward(self)+self.bias

In [59]:
model_5_bias_only=Morning_english_greetings(model20To100_bias_learn_only)

In [15]:
model20To100_bias_learn_only = ResNet9(3, 100, True)
model20To100_bias_learn_only.classifier_child = nn.Sequential(model20To100_bias_learn_only.classifier_parent,
                                        nn.ReLU(),
                                        nn.Linear(20, 10),
                                        nn.ReLU(),
                                        nn.Linear(10, 5)
                                        )
model20To100_bias_learn_only.load_state_dict(torch.load('group20To100_parent_child_60percent_acc_pretrained_model.h5'))
for param in model20To100_bias_learn_only.parameters():
    param.requires_grad=False

delete_this_shit=nn.Sequential(model20To100_bias_learn_only,nn.Linear(5,5))
for param in delete_this_shit.named_parameters():
    print(param)

('0.conv1.0.weight', Parameter containing:
tensor([[[[ 0.0644,  0.0163, -0.0921],
          [-0.0911, -0.0163,  0.1211],
          [-0.0531,  0.0112,  0.0894]],

         [[ 0.0369, -0.0146, -0.0756],
          [-0.0324, -0.1133,  0.0155],
          [-0.0588,  0.0058,  0.0652]],

         [[ 0.1604, -0.0345,  0.0778],
          [ 0.0627,  0.0934, -0.1625],
          [-0.0781, -0.0722,  0.0732]]],


        [[[-0.1360, -0.0719, -0.0374],
          [-0.0587, -0.1320,  0.0554],
          [ 0.0083,  0.0891, -0.0541]],

         [[-0.0530,  0.1490, -0.0930],
          [-0.0704,  0.1148,  0.0239],
          [ 0.0969, -0.0404,  0.1078]],

         [[-0.0285,  0.1033,  0.0954],
          [-0.1021, -0.0623, -0.0200],
          [-0.1544,  0.1113,  0.1362]]],


        [[[ 0.0407,  0.0103, -0.0578],
          [ 0.0668, -0.1586,  0.1044],
          [ 0.0516, -0.1324,  0.0711]],

         [[ 0.1408,  0.0509, -0.0915],
          [ 0.0722, -0.0939, -0.0706],
          [-0.0410,  0.0904, -0.0484]],

 

In [137]:
for param in delete_this_shit.named_parameters():
    #print(param)
    #param[1].data=nn.parameter.Parameter(torch.eye(5))
    #param[1].requires_grad=False
    #print("---------")
    #print(param)
    break

#print(delete_this_shit.named_parameters())
with torch.no_grad():
    delete_this_shit[1].weight= nn.Parameter(torch.eye(5))
    delete_this_shit[1].weight.requires_grad=False
    #model[0].weight[0, 0] = 2.
    #model[0].weight.fill_(3.)

#for param in delete_this_shit.named_parameters():
    #print(param)
    #param[1].data=nn.parameter.Parameter(torch.eye(5))
    #param[1].requires_grad=False
    #print("---------")
    #print(param)
    #break
#=False
#for param in delete_this_shit.named_parameters():
    #print(param)   
delete_this_shit=to_device(delete_this_shit, device)
#print(summary(delete_this_shit,(3, 32, 32)))

In [135]:
# with torch.no_grad():
#     print(delete_this_shit[1].weight)
#     print(delete_this_shit[1].weight.requires_grad)
#     delete_this_shit[1].weight.requires_grad=False
#     print(delete_this_shit[1].weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], device='cuda:0', requires_grad=True)
True
Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], device='cuda:0')


In [138]:
print(summary(delete_this_shit,(3, 32, 32)))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1           [-1, 64, 32, 32]           1,792
       BatchNorm2d-2           [-1, 64, 32, 32]             128
              ReLU-3           [-1, 64, 32, 32]               0
            Conv2d-4          [-1, 128, 32, 32]          73,856
       BatchNorm2d-5          [-1, 128, 32, 32]             256
              ReLU-6          [-1, 128, 32, 32]               0
         MaxPool2d-7          [-1, 128, 16, 16]               0
            Conv2d-8          [-1, 128, 16, 16]         147,584
       BatchNorm2d-9          [-1, 128, 16, 16]             256
             ReLU-10          [-1, 128, 16, 16]               0
           Conv2d-11          [-1, 128, 16, 16]         147,584
      BatchNorm2d-12          [-1, 128, 16, 16]             256
             ReLU-13          [-1, 128, 16, 16]               0
           Conv2d-14          [-1, 256,

In [139]:
for param in delete_this_shit.named_parameters():
    print(param)

('0.conv1.0.weight', Parameter containing:
tensor([[[[ 0.0644,  0.0163, -0.0921],
          [-0.0911, -0.0163,  0.1211],
          [-0.0531,  0.0112,  0.0894]],

         [[ 0.0369, -0.0146, -0.0756],
          [-0.0324, -0.1133,  0.0155],
          [-0.0588,  0.0058,  0.0652]],

         [[ 0.1604, -0.0345,  0.0778],
          [ 0.0627,  0.0934, -0.1625],
          [-0.0781, -0.0722,  0.0732]]],


        [[[-0.1360, -0.0719, -0.0374],
          [-0.0587, -0.1320,  0.0554],
          [ 0.0083,  0.0891, -0.0541]],

         [[-0.0530,  0.1490, -0.0930],
          [-0.0704,  0.1148,  0.0239],
          [ 0.0969, -0.0404,  0.1078]],

         [[-0.0285,  0.1033,  0.0954],
          [-0.1021, -0.0623, -0.0200],
          [-0.1544,  0.1113,  0.1362]]],


        [[[ 0.0407,  0.0103, -0.0578],
          [ 0.0668, -0.1586,  0.1044],
          [ 0.0516, -0.1324,  0.0711]],

         [[ 0.1408,  0.0509, -0.0915],
          [ 0.0722, -0.0939, -0.0706],
          [-0.0410,  0.0904, -0.0484]],

 

In [140]:
history = evaluate(delete_this_shit, testloader)

AttributeError: 'Sequential' object has no attribute 'validation_step'

In [16]:
new_delete=model20To100_bias_learn_only
new_delete.classifier_child=nn.Sequential(new_delete.classifier_child,nn.Linear(5,5))
for param in new_delete.named_parameters():
    print(param)

('conv1.0.weight', Parameter containing:
tensor([[[[ 0.0644,  0.0163, -0.0921],
          [-0.0911, -0.0163,  0.1211],
          [-0.0531,  0.0112,  0.0894]],

         [[ 0.0369, -0.0146, -0.0756],
          [-0.0324, -0.1133,  0.0155],
          [-0.0588,  0.0058,  0.0652]],

         [[ 0.1604, -0.0345,  0.0778],
          [ 0.0627,  0.0934, -0.1625],
          [-0.0781, -0.0722,  0.0732]]],


        [[[-0.1360, -0.0719, -0.0374],
          [-0.0587, -0.1320,  0.0554],
          [ 0.0083,  0.0891, -0.0541]],

         [[-0.0530,  0.1490, -0.0930],
          [-0.0704,  0.1148,  0.0239],
          [ 0.0969, -0.0404,  0.1078]],

         [[-0.0285,  0.1033,  0.0954],
          [-0.1021, -0.0623, -0.0200],
          [-0.1544,  0.1113,  0.1362]]],


        [[[ 0.0407,  0.0103, -0.0578],
          [ 0.0668, -0.1586,  0.1044],
          [ 0.0516, -0.1324,  0.0711]],

         [[ 0.1408,  0.0509, -0.0915],
          [ 0.0722, -0.0939, -0.0706],
          [-0.0410,  0.0904, -0.0484]],

   

In [17]:
with torch.no_grad():
    print(new_delete.classifier_child[1].weight)
    new_delete.classifier_child[1].weight= nn.Parameter(torch.eye(5))
    new_delete.classifier_child[1].weight.requires_grad=False
    print(new_delete.classifier_child[1].weight)
    print(new_delete.classifier_child[1].bias)


new_delete=to_device(new_delete, device)

Parameter containing:
tensor([[-0.1070,  0.1932, -0.4286, -0.3596, -0.0156],
        [-0.2834,  0.1562, -0.1440, -0.0019,  0.4258],
        [ 0.1749, -0.0324,  0.2361, -0.2321,  0.2379],
        [ 0.0756, -0.2832, -0.2482, -0.3514, -0.3148],
        [ 0.3457, -0.4065,  0.4232, -0.1660, -0.1170]], requires_grad=True)
Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Parameter containing:
tensor([0.4044, 0.1985, 0.1189, 0.1842, 0.3492], requires_grad=True)


In [151]:
for param in new_delete.named_parameters():
    print(param)

('conv1.0.weight', Parameter containing:
tensor([[[[ 0.0644,  0.0163, -0.0921],
          [-0.0911, -0.0163,  0.1211],
          [-0.0531,  0.0112,  0.0894]],

         [[ 0.0369, -0.0146, -0.0756],
          [-0.0324, -0.1133,  0.0155],
          [-0.0588,  0.0058,  0.0652]],

         [[ 0.1604, -0.0345,  0.0778],
          [ 0.0627,  0.0934, -0.1625],
          [-0.0781, -0.0722,  0.0732]]],


        [[[-0.1360, -0.0719, -0.0374],
          [-0.0587, -0.1320,  0.0554],
          [ 0.0083,  0.0891, -0.0541]],

         [[-0.0530,  0.1490, -0.0930],
          [-0.0704,  0.1148,  0.0239],
          [ 0.0969, -0.0404,  0.1078]],

         [[-0.0285,  0.1033,  0.0954],
          [-0.1021, -0.0623, -0.0200],
          [-0.1544,  0.1113,  0.1362]]],


        [[[ 0.0407,  0.0103, -0.0578],
          [ 0.0668, -0.1586,  0.1044],
          [ 0.0516, -0.1324,  0.0711]],

         [[ 0.1408,  0.0509, -0.0915],
          [ 0.0722, -0.0939, -0.0706],
          [-0.0410,  0.0904, -0.0484]],

   

In [150]:
print(summary(new_delete,(3, 32, 32)))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1           [-1, 64, 32, 32]           1,792
       BatchNorm2d-2           [-1, 64, 32, 32]             128
              ReLU-3           [-1, 64, 32, 32]               0
            Conv2d-4          [-1, 128, 32, 32]          73,856
       BatchNorm2d-5          [-1, 128, 32, 32]             256
              ReLU-6          [-1, 128, 32, 32]               0
         MaxPool2d-7          [-1, 128, 16, 16]               0
            Conv2d-8          [-1, 128, 16, 16]         147,584
       BatchNorm2d-9          [-1, 128, 16, 16]             256
             ReLU-10          [-1, 128, 16, 16]               0
           Conv2d-11          [-1, 128, 16, 16]         147,584
      BatchNorm2d-12          [-1, 128, 16, 16]             256
             ReLU-13          [-1, 128, 16, 16]               0
           Conv2d-14          [-1, 256,

In [18]:
history = evaluate(new_delete, testloader)

In [19]:
history

{'val_loss': 1.0994218587875366, 'val_acc': 0.6060000061988831}

In [20]:
current_time=time.time()
history += fit_one_cycle(int(epochs), max_lr, new_delete, trainloader, testloader, 
                             grad_clip=grad_clip, 
                             weight_decay=weight_decay, 
                             opt_func=opt_func)

Epoch [0], last_lr: 0.00004, train_loss: 0.5946, val_loss: 1.1025, val_acc: 0.6020
Epoch [1], last_lr: 0.00005, train_loss: 0.6164, val_loss: 1.1019, val_acc: 0.6060
Epoch [2], last_lr: 0.00005, train_loss: 0.6036, val_loss: 1.1015, val_acc: 0.6060
Epoch [3], last_lr: 0.00007, train_loss: 0.6216, val_loss: 1.0994, val_acc: 0.6060
Epoch [4], last_lr: 0.00008, train_loss: 0.6159, val_loss: 1.1015, val_acc: 0.6040
Epoch [5], last_lr: 0.00010, train_loss: 0.6082, val_loss: 1.1013, val_acc: 0.6040
Epoch [6], last_lr: 0.00012, train_loss: 0.6189, val_loss: 1.0997, val_acc: 0.6040
Epoch [7], last_lr: 0.00015, train_loss: 0.6123, val_loss: 1.1023, val_acc: 0.6080
Epoch [8], last_lr: 0.00018, train_loss: 0.6196, val_loss: 1.1034, val_acc: 0.6060
Epoch [9], last_lr: 0.00021, train_loss: 0.6347, val_loss: 1.1034, val_acc: 0.6040
Epoch [10], last_lr: 0.00024, train_loss: 0.6159, val_loss: 1.0998, val_acc: 0.6060
Epoch [11], last_lr: 0.00028, train_loss: 0.6017, val_loss: 1.1007, val_acc: 0.6040
Ep

TypeError: unsupported operand type(s) for +=: 'dict' and 'list'

In [ ]:
y_test, y_pred = test_label_predictions(model20To100, device, testloader)
cm=confusion_matrix(y_test, y_pred)
cr=classification_report(y_test, y_pred)
fs=f1_score(y_test,y_pred,average='weighted')
rs=recall_score(y_test, y_pred,average='weighted')
accuracy=accuracy_score(y_test, y_pred)
print('Confusion matrix:')
print(cm)
print(cr)
print('F1 score: %f' % fs)
print('Recall score: %f' % rs)
print('Accuracy score: %f' % accuracy)

In [ ]:
print(summary(model20To100,(3, 32, 32)))